# Generated by Django 4.0.1 on 2022-01-10 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('image_file', models.FileField(null=True, upload_to='images/')),
                ('delete_status', models.BooleanField(blank=True, null=True)),
                ('created_user_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_user_id', models.CharField(max_length=100)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
