# Generated by Django 4.0.1 on 2022-01-11 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0007_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='delete_status',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
