# Generated by Django 4.0.1 on 2022-01-11 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0008_post_delete_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='private',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
