# Generated by Django 4.0.1 on 2022-01-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0009_post_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='delete_status',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='private',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
